name: CI BUN

on:
  pull_request:
    branches: 
      - develop
      - 'feat/**'
      - 'fix/**'
      - 'chore/**'

jobs: 
  
  code-quality-bun:
    name: Code Quality BUN
<<<<<<< HEAD
=======
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with: 
          bun-version: 1.0.0
      - name: Install dependencies
        run: bun install --silent # --no-audit --no-fund --no-optional

      - name: Linter
        run: bun run lint

      - name: Tests
        run: bun run test:cov -- -u

      - name: Build
        run: bun build ./src/main.tsx --outdir ./dist --public-path ./public --analyze

      - uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: coverage
  
  code-quality-npm: 
    name: Code Quality NPM
>>>>>>> f39ea510b668467660f44d1a658e737930f84b4b
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with: 
          bun-version: 1.0.0
      - name: Install dependencies
        run: bun install --silent # --no-audit --no-fund --no-optional

      - name: Linter
        run: bun run lint

      - name: Tests
        run: bun run test:cov -- -u

      - name: Build
        run: bun build ./src/main.tsx --outdir ./dist --public-path ./public --analyze
  
      - name: Build with vite
        run: bun run build

      - uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: coverage
  
  code-quality-npm: 
    name: Code Quality NPM
    strategy:
      matrix:
        version: [16, 18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }} # si no se pasa la variable runs-on ejecuta todas las combinaciones posibles de os y version
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: 
<<<<<<< HEAD
          node-version: ${{ matrix.version }}
=======
          node-version: 18
>>>>>>> f39ea510b668467660f44d1a658e737930f84b4b
      - name: Install dependencies
        run: npm ci # --no-audit --no-fund --no-optional

      - name: Linter
        run: npm run lint

      - name: Tests
        run: npm run test:cov -- -u

      - name: Build
        run: npm run build
