name: CI BUN

on:
  pull_request:
    branches: [develop, main]

jobs: 
  
  code-quality-bun:
    name: Code Quality BUN
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with: 
          bun-version: 1.0.0
      - name: Install dependencies
        run: bun install --silent # --no-audit --no-fund --no-optional

      - name: Linter
        run: bun run lint

      - name: Tests
        run: bun run test:cov -- -u

      - name: Build
        run: bun build ./src/main.tsx --outdir ./dist --public-path ./public --analyze

      - uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: coverage
  
  code-quality-npm: 
    name: Code Quality NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm ci # --no-audit --no-fund --no-optional

      - name: Linter
        run: npm run lint

      - name: Tests
        run: npm run test:cov -- -u

      - name: Build
        run: npm run build
