name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs: 
  
  test-cov:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      
      - name: Install dependencies
        run: npm ci # --no-audit --no-fund --no-optional

      - name: Linter
        run: npm run lint

      - name: Tests
        run: npm run test:cov

      - name: Build
        run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: coverage

      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
