name: Tests

on:
  pull_request:
    branches: [develop, main]

jobs: 
  
  test-cov:
    name: Test coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      
      - name: Install dependencies
        run: npm ci

      - name: Tests
        run: npm run test:cov

      - uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: coverage/index.html
