name: Tests

on:
  pull_request:
    branches: [develop, main]

jobs: 
  execute-test:
    name: set up job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm ci
      - run: npm run test:cov